[project]
name = "app"
version = "0.1.0"
description = "Sistema Integral de Gestión y Automatización de Parqueaderos."
requires-python = ">=3.14,<4.0"
dependencies = [
    "fastapi[standard-no-fastapi-cloud-cli]>=0.142.2,<1.0.0",
    "psycopg[binary,pool]>=3.3.6",
    "sqlmodel>=0.0.47",
    "loguru>=0.7.3",
]

[dependency-groups]
dev = [
    "httpx>=0.28.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
]

[tool.fastapi]
entrypoint = "src.server.main:app"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
